// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFpwivddWGBZYYce4txSYsZ17Wc-qAzfg',
    appId: '1:641860910758:web:e8059dc9ab456888bc3e67',
    messagingSenderId: '641860910758',
    projectId: 'focus-n-flow-dm',
    authDomain: 'focus-n-flow-dm.firebaseapp.com',
    storageBucket: 'focus-n-flow-dm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2iCzQYRBNSb0w3CN8PHCR7lKcfZgCpuI',
    appId: '1:641860910758:android:3f90b42f238fd128bc3e67',
    messagingSenderId: '641860910758',
    projectId: 'focus-n-flow-dm',
    storageBucket: 'focus-n-flow-dm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAefLyDEQjytLa44rJsOu0kBf-E2JfiVwM',
    appId: '1:641860910758:ios:1834b458916b5cc0bc3e67',
    messagingSenderId: '641860910758',
    projectId: 'focus-n-flow-dm',
    storageBucket: 'focus-n-flow-dm.firebasestorage.app',
    iosBundleId: 'com.example.focusNFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAefLyDEQjytLa44rJsOu0kBf-E2JfiVwM',
    appId: '1:641860910758:ios:1834b458916b5cc0bc3e67',
    messagingSenderId: '641860910758',
    projectId: 'focus-n-flow-dm',
    storageBucket: 'focus-n-flow-dm.firebasestorage.app',
    iosBundleId: 'com.example.focusNFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFpwivddWGBZYYce4txSYsZ17Wc-qAzfg',
    appId: '1:641860910758:web:040e1e2203eb7148bc3e67',
    messagingSenderId: '641860910758',
    projectId: 'focus-n-flow-dm',
    authDomain: 'focus-n-flow-dm.firebaseapp.com',
    storageBucket: 'focus-n-flow-dm.firebasestorage.app',
  );
}
